M48
; DRILL file {KiCad 8.0.0} date 2024-10-16T16:52:37+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-16T16:52:37+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0669
%
G90
G05
T1
X6.3586Y-2.8782
X6.3586Y-3.1058
T2
X6.1286Y-4.9643
X6.4042Y-4.9643
M30
